// PLACEHOLDER — regenerate with: flutterfire configure --project=cameroon-innovation --platforms=android
//
// The real file is generated by `flutterfire configure`, which requires a
// Firebase login and the real project. That step is credential-blocked in this
// environment, so this placeholder exists only so that files importing
// `firebase_options.dart` continue to analyze and compile. Pure-Dart
// `flutter test` does not need real config; running the app does.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
        apiKey: 'PLACEHOLDER',
        appId: 'PLACEHOLDER',
        messagingSenderId: 'PLACEHOLDER',
        projectId: 'cameroon-innovation',
      );
}
